user_info_0: {bp: '4902', deviceName: '9509426', port: '4702'}
user_info_1: {bp: '4903', deviceName: 37b34d04, port: '4703'}
user_info_0: {bp: '4902', deviceName: '9509426', port: '4702'}
user_info_1: {bp: '4903', deviceName: 37b34d04, port: '4703'}
user_info_0: {bp: '4902', deviceName: '9509426', port: '4702'}
user_info_1: {bp: '4903', deviceName: 37b34d04, port: '4703'}
