user_info_0: {bp: '4900', deviceName: '9509426', port: '4700'}
user_info_1: {bp: '4908', deviceName: 37b34d04, port: '4703'}
user_info_0: {bp: '4900', deviceName: '9509426', port: '4700'}
user_info_1: {bp: '4908', deviceName: 37b34d04, port: '4703'}
user_info_0: {bp: '4900', deviceName: '9509426', port: '4700'}
user_info_1: {bp: '4908', deviceName: 37b34d04, port: '4703'}
